# Generated by Django 4.1.10 on 2023-07-18 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HeartRate', 'HeartRate'), ('StepCount', 'StepCount'), ('SleepAnalysis', 'SleepAnalysis'), ('BloodGlucose', 'BloodGlucose')], max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('metadata', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
